=== wilsonpilon/fwMSX/resource/msxide/paleobasic/resource/nestor/DOC/UNAPI/SRC/rfc2629.dtd
<!--
     revised DTD for the RFC document series, draft of 2002-01-20
     -->


   <!--
     Contents

       DTD data types

       The top-level

       Front matter

       The Body

       Back matter
     -->


   <!--
     DTD data types:

           entity        description
           ======        ===============================================
           NUMBER        [0-9]+
           NUMBERS       a comma-separated list of NUMBER

           DAY           the day of the month, e.g., "1"
           MONTH         the month of the year, e.g., "January"
           YEAR          a four-digit year, e.g., "1999"

           URI           e.g., "http://invisible.net/"

           ATEXT/CTEXT   printable ASCII text (no line-terminators)

           TEXT          character data
     -->


   <!ENTITY % NUMBER     "CDATA">
   <!ENTITY % NUMBERS    "CDATA">

   <!ENTITY % DAY        "CDATA">
   <!ENTITY % MONTH      "CDATA">
   <!ENTITY % YEAR       "CDATA">

   <!ENTITY % URI        "CDATA">

   <!ENTITY % ATEXT      "CDATA">
   <!ENTITY % CTEXT      "#PCDATA">

   <!ENTITY % TEXT       "#PCDATA">

   <!ENTITY   rfc.number "XXXX">


   <!--
     The top-level
     -->


   <!--
     attributes for the "rfc" element are supplied by the RFC
     editor. when preparing drafts, authors should leave them blank.

     the "seriesNo" attribute is used if the category is, e.g., BCP.
     -->
   <!ELEMENT rfc         (front,middle,back?)>
   <!ATTLIST rfc
             number      %NUMBER;           #IMPLIED
             obsoletes   %NUMBERS;          ""
             updates     %NUMBERS;          ""
             category    (std|bcp|info|exp|historic)
                                            "info"
             seriesNo    %NUMBER;           #IMPLIED
             ipr         (full2026|noDerivativeWorks2026|none
                         |full3667|noModification3667|noDerivatives3667
                         |full3978|noModification3978|noDerivatives3978)
                                            #IMPLIED
             iprExtract  ID                 #IMPLIED
             docName     %ATEXT;            #IMPLIED
             xml:lang    %ATEXT;            "en">


   <!--
     Front matter
     -->


   <!ELEMENT front       (title,author+,date,area*,workgroup*,keyword*,
                          abstract?,note*)>

   <!-- the "abbrev" attribute is used for headers, etc. -->
   <!ELEMENT title       (%CTEXT;)>

   <!ATTLIST title
             abbrev      %ATEXT;            #IMPLIED>

   <!ELEMENT author      (organization,address?)>
   <!ATTLIST author
             initials    %ATEXT;            #IMPLIED
             surname     %ATEXT;            #IMPLIED
             fullname    %ATEXT;            #IMPLIED
             role        (editor)           #IMPLIED>

   <!ELEMENT organization
                         (%CTEXT;)>
   <!ATTLIST organization
             abbrev      %ATEXT;            #IMPLIED>

   <!ELEMENT address     (postal?,phone?,facsimile?,email?,uri?)>

   <!-- this content model should be more strict:
        at most one of each the city, region, code, and country
        elements may be present -->
   <!ELEMENT postal      (street+,(city|region|code|country)*)>
   <!ELEMENT street      (%CTEXT;)>
   <!ELEMENT city        (%CTEXT;)>
   <!ELEMENT region      (%CTEXT;)>
   <!ELEMENT code        (%CTEXT;)>
   <!ELEMENT country     (%CTEXT;)>
   <!ELEMENT phone       (%CTEXT;)>
   <!ELEMENT facsimile   (%CTEXT;)>
   <!ELEMENT email       (%CTEXT;)>
   <!ELEMENT uri         (%CTEXT;)>

   <!ELEMENT date        EMPTY>
   <!ATTLIST date
             day         %DAY;              #IMPLIED
             month       %MONTH;            #IMPLIED
             year        %YEAR;             #IMPLIED>

   <!-- meta-data... -->
   <!ELEMENT area        (%CTEXT;)>
   <!ELEMENT workgroup   (%CTEXT;)>
   <!ELEMENT keyword     (%CTEXT;)>

   <!ELEMENT abstract    (t)+>
   <!ELEMENT note        (t)+>
   <!ATTLIST note
             title       %ATEXT;            #REQUIRED>

   <!--
     The body
     -->


   <!ELEMENT middle      (section+,appendix*,section*)>

   <!ELEMENT section     (t|figure|texttable|iref|section)*>
   <!ATTLIST section
             anchor      ID                 #IMPLIED
             title       %ATEXT;            #REQUIRED
             toc         (include|exclude|default)
                                            "default">

   <!ELEMENT appendix    (t|figure|texttable|iref|appendix)*>
   <!ATTLIST appendix
             anchor      ID                 #IMPLIED
             title       %ATEXT;            #REQUIRED
             toc         (include|exclude|default)
                                            "default">

   <!-- use of <figure/> is deprecated... -->
   <!ELEMENT t
             (%TEXT;|list|figure|xref|eref|iref|cref|spanx|vspace)*>
   <!ATTLIST t
             hangText    %ATEXT;            #IMPLIED>

   <!-- the value of the style attribute is inherited from the closest
        parent -->
   <!ELEMENT list        (t+)>
   <!ATTLIST list
             style       %ATEXT;            "empty"
             hangIndent  %NUMBER;           #IMPLIED
             counter     %ATEXT;            #IMPLIED>

   <!ELEMENT xref        (%CTEXT;)>
   <!ATTLIST xref
             target      IDREF              #REQUIRED
             pageno      (true|false)       "false"
             format      (counter|title|default)
                                            "default">

   <!ELEMENT eref        (%CTEXT;)>
   <!ATTLIST eref
             target      %URI;              #REQUIRED>

   <!ELEMENT iref        EMPTY>
   <!ATTLIST iref

             item        %ATEXT;            #REQUIRED
             subitem     %ATEXT;            ""
             primary    (true|false)       "false">

   <!ELEMENT cref        (%CTEXT;)>
   <!ATTLIST cref
             anchor      ID                 #IMPLIED
             source      %ATEXT;            #IMPLIED>

   <!ELEMENT spanx       (%CTEXT;)>
   <!ATTLIST spanx
             style       %ATEXT;            "emph">

   <!ELEMENT vspace      EMPTY>
   <!ATTLIST vspace
             blankLines  %NUMBER;           "0">

   <!ELEMENT figure      (preamble?,artwork,postamble?)>
   <!ATTLIST figure
             anchor      ID                 #IMPLIED
             title       %ATEXT;            ""
             src         %URI;              #IMPLIED
             align       (left|center|right) "left"
             alt         %ATEXT;            ""
             width       %ATEXT;            ""
             height      %ATEXT;            "">

   <!ELEMENT preamble    (%TEXT;|xref|eref|iref|cref|spanx)*>
   <!ELEMENT artwork     (%TEXT;)*>
   <!ATTLIST artwork
             xml:space   (default|preserve) "preserve"
             name        %ATEXT;            ""
             type        %ATEXT;            ""
             src         %URI;              #IMPLIED
             align       (left|center|right) "left"
             alt         %ATEXT;            ""
             width       %ATEXT;            ""
             height      %ATEXT;            "">

   <!ELEMENT postamble   (%TEXT;|xref|eref|iref|cref|spanx)*>

   <!ELEMENT texttable   (preamble?,ttcol+,c*,postamble?)>
   <!ATTLIST texttable
             anchor      ID                 #IMPLIED
             title       %ATEXT;            "">
   <!ELEMENT ttcol       (%CTEXT;)>
   <!ATTLIST ttcol
             width       %ATEXT;           #IMPLIED

             align       (left|center|right) "left">
   <!ELEMENT c           (%TEXT;|xref|eref|iref|cref|spanx)*>


   <!--
     Back matter
     -->


   <!-- sections, if present, are appendices -->
   <!ELEMENT back        (references*,section*)>

   <!ELEMENT references  (reference+)>
   <!ATTLIST references
             title       %ATEXT;            "References">
   <!ELEMENT reference   (front,seriesInfo*,format*,annotation*)>
   <!ATTLIST reference
             anchor      ID                 #IMPLIED
             target      %URI;              #IMPLIED>
   <!ELEMENT seriesInfo  EMPTY>
   <!ATTLIST seriesInfo
             name        %ATEXT;            #REQUIRED
             value       %ATEXT;            #REQUIRED>
   <!ELEMENT format      EMPTY>
   <!ATTLIST format
             target      %URI;              #IMPLIED
             type        %ATEXT;            #REQUIRED
             octets      %NUMBER;           #IMPLIED>
   <!ELEMENT annotation  (%TEXT;|xref|eref|iref|cref|spanx)*>

=== wilsonpilon/fwMSX/resource/fmsxgo/third-party/nestor/DOC/UNAPI/SRC/unapiintro-s.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">

<?rfc toc="yes" ?>
<?rfc topblock="yes" ?>
<?rfc symrefs="yes" ?>
<?rfc sortrefs="yes" ?>
<?rfc compact="yes" ?>
<?rfc private="Version 0.2" ?>

<rfc ipr="full3978" docName="UNAPI_INTRO">

	<!-- Header -->

	<front>
		<title abbrev="MSX-UNAPI">Introducción a MSX-UNAPI</title>
		<author initials="N." surname="Soriano" fullname="Nestor Soriano">
			<organization>Comunidad MSX</organization>
			<address>
				<email>konamiman@konamiman.com</email>
				<uri>http://www.konamiman.com</uri>
			</address>
		</author>
		<date month="Julio" year="2007" />
		<abstract>
			<t>Este documento es una introducción a MSX-UNAPI, un procedimiento estandar para definir, descubrir y utilizar nuevas APIs (Application Program Interface)
			para ordenadores MSX. La especificación detallada se encuentra en un documento aparte (especificación MSX-UNAPI).</t>
		</abstract>
	</front>

	<middle>
	
		<!-- Motivation -->
	
		<section anchor="motivation" title="Motivacion">
			<t>Durante los últimos años muchos aficionados al MSX han desarrollado hardware amateur para estas máquinas.
			Normalmente, este hardware incorpora una ROM que contiene un API (Application Program Interface), consistente
			en un conjunto de rutinas que permiten a los desarrolladores interactuar con el hardware.</t>
			<t>Dado que cada dispositivo tiene su propio API, estos no son intercambiables desde el punto de vista del software.
			Por ejemplo, InterNestor Lite sólo funciona con la tarjeta ethernet ObsoNET, y no funcionará con ninguna otra tarjeta
			ethernet desarrollada en el futuro.</t>
			<t>El objetivo de la especificación MSX-UNAPI es resolver este problema, para lo cual define una serie de reglas a seguir
			para crear implementaciones intercambiables de APIs.</t>
		</section>

		<!-- Key concepts -->
		
		<section anchor="key_concepts" title="Conceptos clave">
			<t>La especificación completa de MSX-UNAPI puede parecer complicada a primera vista, pero está basada en únicamente unos pocos
			conceptos clave, enumerados a continuación.</t>
			<t>Nota: En el texto que sigue, los términos "especificación API" e "implementación API" hacen referencia a especificaciones
			e implementaciones de APIs que siguen las reglas de la especificación MSX-UNAPI.</t>
			<vspace blankLines='1' />
				<list style="symbols">
					<t>Una "especificación API" es un conjunto de rutinas que realizan una serie de tareas concretas. Cada especificación
					tiene asignada un identificador alfanumérico corto que sirve para distinguirla de forma inequívoca de otras especificaciones.</t>
					<vspace blankLines='1' />
					<list style="empty">
						<t>Por ejemplo, la especificación de un API para tarjetas ethernet podría tener el identificador ETHERNET y estar compuesto
						de tres rutinas: enviar paquete, recibir paquete y comprobar el estado de la red.</t>
					</list>
					<vspace blankLines='1' />
					<t>Una "implementación API" es la plasmación en código de una especificación API. Pueden existir múltiples implementaciones
					de la misma especificación, y dado que todas ellas implementan el mismo juego de rutinas, son intercambiables.
					Cada implementación tiene un nombre corto que sirve para distinguirla de otras implementaciones.</t>
					<vspace blankLines='1' />
					<list style="empty">
						<t>Por ejemplo, "ObsoNET BIOS" y "Dumas BIOS" podrían ser los nombres de dos implementaciones del API
						cuyo identificador es ETHERNET. Una pila TCP/IP preparada para manejar la API ETHERNET sería capaz de trabajar
						con ambas implementaciones.</t>
					</list>
					<vspace blankLines='1' />
					<t>La especificación MSX-UNAPI proporciona un conjunto básico de reglas que deben ser seguidas por todas las especificaciones
					e implementaciones de APIs. Esto tiene como objetivo facilitar el desarrollo del software que hace uso de implementaciones de APIs.</t>
					<vspace blankLines='1' />
					<list style="empty">
						<t>Las reglas principales son: el código de una implementación API debe residir en ROM, en RAM mapeada o en la RAM de la página 3;
						debe haber un único punto de llamada para todas las rutinas (el número de rutina se pasa en el registro A);
						y debe existir una rutina que informe del nombre y la versión de la implementación API. Todo esto se explica con detalle
						en el documento "especificación MSX-UNAPI".</t>
					</list>
					<vspace blankLines='1' />
					<t>Es posible que varias implementaciones de una misma especificación API sean instaladas simultáneamente.
					El mecanismo de BIOS extendida del MSX se usa para descubrir la presencia y la ubicación de las implementaciones disponibles.</t>
					<vspace blankLines='1' />
					<list style="empty">
						<t>Normalmente, si se encuentra más de una implementación de un mismo API, no importa cuál se usa para realizar
						las tareas ofrecidas por la especificación API. Sin embargo, en caso necesario, las implementaciones pueden
						ser distinguidas gracias a sus nombres.</t>
					</list>
				</list>
		</section>

		<!-- Example -->
		
		<section anchor="example" title="Ejemplo">
			<t>Este ejemplo muestra el pseudo-codigo de una hipotética pila TCP/IP que usa la API ETHERNET para enviar y recibir datos.
			En el código, los nombres A, B, C, HL y DE hacen referencia a registros del Z80; otros nombres hacen referencia a rutinas o variables.
			El símbolo de punto y coma (;) indica que el resto de la línea es un comentario.</t>
			<t>El documento "especificación MSX-UNAPI" proporciona información detallada sobre el uso de las rutinas API, el uso de la BIOS extendida
			y el uso de los registros del Z80.</t>
			<vspace blankLines='1' />
			<list style="empty">
				<t>PRINT "¡Bienvenido a esta pila TCP/IP para la API ETHERNET!"</t>
				<t>PRINT "Voy a buscar implementaciones de la API ETHERNET API..."</t>
				<vspace blankLines='1' />
				<t>POKE &HF847,"ETHERNET"+0</t>
				<t>A=0</t>
				<t>B=0</t>
				<t>DE=&H2222</t>
				<t>CALL &HFFCA  ; El gancho EXTBIO</t>
				<vspace blankLines='1' />
				<t>IF B=0 THEN</t>
				<list style="empty">
					<t>PRINT "¡Ooops!"</t>
					<t>PRINT "¡No he encontrado implementaciones de la API ETHERNET!"</t>
					<t>END</t>
				</list>
				<t>ENDIF</t>
				<vspace blankLines='1' />
				<t>PRINT "He encontrado "+B+" implementaciones de la API ETHERNET"</t>
				<t>PRINT "Voy a usar la implementacion con índice 1"</t>
				<vspace blankLines='1' />
				<t>; Obtiene la ubicación de la implementación</t>
				<t>; (dirección, slot y/o segmento)</t>
				<t>; y como primera tarea obtiene su nombre y versión</t>
				<vspace blankLines='1' />
				<t>POKE &HF847,"ETHERNET"+0  ; No necesario si memoria no cambiada</t>
				<t>A=1  ; Indice de la implementación</t>
				<t>DE=&H2222</t>
				<t>CALL &HFFCA  ; El gancho EXTBIO</t>
				<t>ApiSlot=A</t>
				<t>ApiSegment=B</t>
				<t>ApiEntry=HL</t>
				<vspace blankLines='1' />
				<t>A=0  ; 0 es el índice de la rutina de información sobre el API</t>
				<t>CALL EXE_UNAPI</t>
				<t>PRINT "El nombre del API es: "+READ_UNAPI(HL)</t>
				<t>PRINT "La versión del API es: "+B+"."+C</t>
				<vspace blankLines='1' />
				<t>; Supóngase ahora que según la especificación del API ETHERNET,</t>
				<t>; la rutina 3 devuelve A=1 si la red está disponible o 0 si no</t>
				<vspace blankLines='1' />
				<t>A=3</t>
				<t>CALL EXE_UNAPI</t>
				<t>IF A=0 THEN</t>
				<list style="empty">
					<t>PRINT "¡Ooops! ¡No hay red!"</t>
					<t>END</t>
				</list>
				<t>ENDIF</t>
				<vspace blankLines='1' />
				<t>PRINT "¡Red OK! Vamos a internetear."</t>
				<t>; etc etc...</t>
				<vspace blankLines='2' />
				<t>;--- Esta rutina llama a la rutina API cuyo índice se pasa en A</t>
				<vspace blankLines='1' />
				<t>EXE_UNAPI:</t>
				<list style="empty">
					<t>IF ApiEntry>=&HC000 THEN</t>
					<list style="empty">
						<t>CALL ApiEntry</t>
					</list>
					<t>ELSE IF ApiSegment=&HFF THEN</t>
					<list style="empty">
						<t>CALL ApiEntry AT SLOT ApiSlot</t>
					</list>
					<t>ELSE</t>
					<list style="empty">
						<t>CALL ApiEntry AT SEGMENT ApiSegment AT SLOT ApiSlot</t>
					</list>
					<t>RETURN</t>
				</list>
				<vspace blankLines='2' />
				<t>;--- Esta rutina lee la memoria de la implementación API desde</t>
				<t>;--- la dirección pasada como parámetro, hasta encontrar un cero</t>
				<vspace blankLines='1' />
				<t>READ_UNAPI(Address):</t>
				<list style="empty">
					<t>HL=Address</t>
					<t>String=""</t>
					<t>LOOP:</t>
					<t>IF Address>=&HC000 THEN</t>
					<list style="empty">
						<t>A=PEEK(HL)</t>
					</list>
					<t>ELSE IF ApiSegment=&HFF THEN</t>
					<list style="empty">
						<t>A=READ (HL) AT SLOT ApiSlot</t>
					</list>
					<t>ELSE</t>
					<list style="empty">
						<t>A=READ (HL) AT SEGMENT ApiSegment AT SLOT ApiSlot</t>
					</list>
					<t>ENDIF</t>
					<t>IF A<>0 THEN</t>
					<list style="empty">
						<t>String=String+A</t>
						<t>HL=HL+1</t>
						<t>GOTO LOOP</t>
					</list>
					<t>RETURN String</t>
				</list>
						
			</list>
		</section>

		<!-- Appendixes -->

		<back>
			<section title="Agradecimientos">
				<t>Este documento ha sido generado usando xml2rfc v1.32 (en http://xml.resource.org/) a partir de una fuente en formato XML según RFC-2629.</t>
			</section>
			<section title="Historial de versiones del documento">
			<vspace blankLines='1' />
			<list style="symbols">
				<t>Version 0.2</t>
				<list style="symbols">
					<t>Se han realizado varios cambios menores propuestos por Tanni, a fin de clarificar el texto.</t>
				</list>
			</list>
			</section>
		</back>
	</middle>
</rfc>

=== wilsonpilon/fwMSX/resource/fmsxgo/third-party/msxide/paleobasic/resource/nestor/DOC/UNAPI/SRC/unapiintro.xml
<?xml version="1.0"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">

<?rfc toc="yes" ?>
<?rfc topblock="yes" ?>
<?rfc symrefs="yes" ?>
<?rfc sortrefs="yes" ?>
<?rfc compact="yes" ?>
<?rfc private="Version 0.2" ?>

<rfc ipr="full3978" docName="UNAPI_INTRO">

	<!-- Header -->

	<front>
		<title abbrev="MSX-UNAPI">Introduction to MSX-UNAPI</title>
		<author initials="N." surname="Soriano" fullname="Nestor Soriano">
			<organization>MSX community</organization>
			<address>
				<email>konamiman@konamiman.com</email>
				<uri>http://www.konamiman.com</uri>
			</address>
		</author>
		<date month="July" year="2007" />
		<abstract>
			<t>This document introduces MSX-UNAPI, a standard procedure for defining, discovering and using new APIs (Application Program Interfaces)
			for MSX computers. For the detailed specification, please read the MSX-UNAPI specification document.</t>
		</abstract>
	</front>

	<middle>
	
		<!-- Motivation -->
	
		<section anchor="motivation" title="Motivation">
			<t>In the last years, several MSX hobbyists have developed various kinds of amateur hardware for MSX computers.
			Usually, each of these pieces of hardware comes with a ROM containing an API (Application Program Interface), which consists
			of a series of routines that allow developers to interact with the hardware.</t>
			<t>As each device has its own API, devices are not interchangeable from the software point of view. For example, InterNestor Lite
			works only with the ethernet card ObsoNET, and it will not work with any other card developed in the future.</t>
			<t>The MSX-UNAPI specification aims to solve this problem, by defining a set of rules for creating interchangeable
			API implementations.</t>
		</section>

		<!-- Key concepts -->
		
		<section anchor="key_concepts" title="Key concepts">
			<t>The complete MSX-UNAPI specification may seem complicated at first glance, but it relies on just a few key concepts, which are
			enumerated below.</t>
			<t>Note: In the following text, the terms "API specification" and "API implementation" refer to API specifications and implementations
			that obey the rules of the MSX-UNAPI specification.</t>
			<vspace blankLines='1' />
				<list style="symbols">
					<t>An "API specification" is a set of routines for performing a set of concrete tasks. Each specification
					has a short alphanumeric identifier that serves as a signature to uniquely distinguish it from other specifications.</t>
					<vspace blankLines='1' />
					<list style="empty">
						<t>For example, an API specification for ethernet cards could have the identifier ETHERNET and be composed of three routines:
						send packet, receive packet and check network state.</t>
					</list>
					<vspace blankLines='1' />
					<t>An "API implementation" is the realisation in code of an API specification. There may be several implementation
					of the same API specification, and since all of them implement the same set of routines, they are interchangeable.
					Each implementation has a short name that serves to distinguish it from other implementations.</t>
					<vspace blankLines='1' />
					<list style="empty">
						<t>For example, "ObsoNET BIOS" and "Dumas BIOS" could be the names of two implementations of the API
						whose identifier is ETHERNET. A TCP/IP stack prepared to deal with the ETHERNET API could
						work with both implementations.</t>
					</list>
					<vspace blankLines='1' />
					<t>The MSX-UNAPI specification provides a set of minimal rules that must be followed by all compliant API specifications and implementations.
					This is done to ease the development of software that make use of API implementations.</t>
					<vspace blankLines='1' />
					<list style="empty">
						<t>The main rules are: API implementation code must be placed in ROM, in mapped RAM or in page 3 RAM;
						there must be one single call point for all the API routines (routine number is passed in register A);
						and there must be one routine that informs about the API name and version. All of this is detailed
						in the MSX-UNAPI specification document.</t>
					</list>
					<vspace blankLines='1' />
					<t>More than one implementation of a given API specification may be installed at the same time.
					The MSX extended BIOS mechanism is used to discover and locate the available implementations.</t>
					<vspace blankLines='1' />
					<list style="empty">
						<t>Usually, when more than one implementation is found, it does not matter which one is used
						to perform the tasks offered by the API specification. However, if necessary, implementations
						can be distinguished thanks to their names.</t>
					</list>
				</list>
		</section>

		<!-- Example -->
		
		<section anchor="example" title="Example">
			<t>This example provides pseudo-code for an hypothetical TCP/IP stack that relies on the ETHERNET API to send and receive data.
			In the code, the names A, B, C, HL and DE refer to Z80 registers; other names refer to routines or variables.
			Semicolons (;) indicate that the rest of the line is a comment.</t>
			<t>Please refer to the MSX-UNAPI specification document for details about how to call API routines and extended BIOS, as well as Z80
			registers usage.</t>
			<vspace blankLines='1' />
			<list style="empty">
				<t>PRINT "Welcome to this wonderful ETHERNET API aware TCP/IP stack!"</t>
				<t>PRINT "Now I'm going to search for ETHERNET API implementations...</t>
				<vspace blankLines='1' />
				<t>POKE &HF847,"ETHERNET"+0</t>
				<t>A=0</t>
				<t>B=0</t>
				<t>DE=&H2222</t>
				<t>CALL &HFFCA  ; The EXTBIO hook</t>
				<vspace blankLines='1' />
				<t>IF B=0 THEN</t>
				<list style="empty">
					<t>PRINT "Ooops!"</t>
					<t>PRINT "I haven't found any ETHERNET API implementation!"</t>
					<t>END</t>
				</list>
				<t>ENDIF</t>
				<vspace blankLines='1' />
				<t>PRINT "I've found "+B+" implementations of the ETHERNET API!"</t>
				<t>PRINT "I'll use implementation with index 1"</t>
				<vspace blankLines='1' />
				<t>; Obtain implementation location (address, slot and/or segment)</t>
				<t>; and as the first task, obtain its name and version</t>
				<vspace blankLines='1' />
				<t>POKE &HF847,"ETHERNET"+0  ; Not necessary if memory not modified</t>
				<t>A=1  ; The implementation index</t>
				<t>DE=&H2222</t>
				<t>CALL &HFFCA  ; The EXTBIO hook</t>
				<t>ApiSlot=A</t>
				<t>ApiSegment=B</t>
				<t>ApiEntry=HL</t>
				<vspace blankLines='1' />
				<t>A=0  ; 0 is the index for the API information routine</t>
				<t>CALL EXE_UNAPI</t>
				<t>PRINT "The API name is: "+READ_UNAPI(HL)</t>
				<t>PRINT "The API version is: "+B+"."+C</t>
				<vspace blankLines='1' />
				<t>; Now assume that per the ETHERNET API specification,</t>
				<t>; routine 3 returns A=1 if network is available or 0 otherwise</t>
				<vspace blankLines='1' />
				<t>A=3</t>
				<t>CALL EXE_UNAPI</t>
				<t>IF A=0 THEN</t>
				<list style="empty">
					<t>PRINT "Ooops! No network!"</t>
					<t>END</t>
				</list>
				<t>ENDIF</t>
				<vspace blankLines='1' />
				<t>PRINT "Network OK! Let's internetwork!"</t>
				<t>; etc etc...</t>
				<vspace blankLines='2' />
				<t>;--- This routine calls the API routine whose index is passed in A</t>
				<vspace blankLines='1' />
				<t>EXE_UNAPI:</t>
				<list style="empty">
					<t>IF ApiEntry>=&HC000 THEN</t>
					<list style="empty">
						<t>CALL ApiEntry</t>
					</list>
					<t>ELSE IF ApiSegment=&HFF THEN</t>
					<list style="empty">
						<t>CALL ApiEntry AT SLOT ApiSlot</t>
					</list>
					<t>ELSE</t>
					<list style="empty">
						<t>CALL ApiEntry AT SEGMENT ApiSegment AT SLOT ApiSlot</t>
					</list>
					<t>RETURN</t>
				</list>
				<vspace blankLines='2' />
				<t>;--- This routine reads the API memory whose address</t>
				<t>;--- is passed as parameter, until a zero is found</t>
				<vspace blankLines='1' />
				<t>READ_UNAPI(Address):</t>
				<list style="empty">
					<t>HL=Address</t>
					<t>String=""</t>
					<t>LOOP:</t>
					<t>IF Address>=&HC000 THEN</t>
					<list style="empty">
						<t>A=PEEK(HL)</t>
					</list>
					<t>ELSE IF ApiSegment=&HFF THEN</t>
					<list style="empty">
						<t>A=READ (HL) AT SLOT ApiSlot</t>
					</list>
					<t>ELSE</t>
					<list style="empty">
						<t>A=READ (HL) AT SEGMENT ApiSegment AT SLOT ApiSlot</t>
					</list>
					<t>ENDIF</t>
					<t>IF A<>0 THEN</t>
					<list style="empty">
						<t>String=String+A</t>
						<t>HL=HL+1</t>
						<t>GOTO LOOP</t>
					</list>
					<t>RETURN String</t>
				</list>
						
			</list>
		</section>

		<!-- Appendixes -->

		<back>
			<section title="Acknowledgements">
				<t>This document was produced using xml2rfc v1.32 (of http://xml.resource.org/) from a source in RFC-2629 XML format.</t>
			</section>
			<section title="Document version history">
			<vspace blankLines='1' />
			<list style="symbols">
				<t>Version 0.2</t>
				<list style="symbols">
					<t>Done some minor changes proposed by Tanni, in order to clarify the text.</t>
				</list>
			</list>
			</section>
		</back>
	</middle>
</rfc>
